name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: docs
          git-user: $SOME_USERNAME
          #git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
      
        
